services:
  mcp_server_gateway:
    depends_on:
      - keycloak
#    build:
#      dockerfile: Dockerfile
#      context: ../mcp-server-gateway
#    volumes:
#    - ../mcp-server-gateway/:/usr/src/mcp_server_gateway/
    image: 875300655693.dkr.ecr.us-east-1.amazonaws.com/mcp-server-gateway:1.0.20
    container_name: mcp-server-gateway
    environment:
      DEBUG_METRICS: 0
      DD_TRACE_ENABLED: "false"
      LOG_LEVEL: DEBUG
      # These define the connection to the identity provider for JWT validation
      AUTH_WELL_KNOWN_URI: "http://keycloak:8085/realms/bwell-realm/.well-known/openid-configuration,https://icanbwell.okta.com/.well-known/openid-configuration"
    env_file: docker.env
    command: ["uvicorn", "mcp_server_gateway.api:app", "--host", "0.0.0.0", "--port", "5000", "--reload", "--log-level", "debug"]
    ports:
      - '5051:5000'
    healthcheck:
      test: curl --fail -s http://localhost:5000/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - web